### ISSUE TITLE
support eslint --fix in 'no-raw-text' rule

### ISSUE THREAD

**Issue by kiibo382** [intlify/eslint-plugin-vue-i18n#202]
This issue is a request to add a fix option to the no-raw-text rule.

For exmaple, 

```.eslintrc.js
module.export = {
  extends: [
    'eslint:recommended',
    'plugin:@intlify/vue-i18n/recommended'
  ],
  rules: {
  },
  settings: {
    'vue-i18n': {
    }
  }
}
```

and run

```bash
eslint --config ./.eslintrc.js --ext .vue,.ts,.js . --fix",
```

before

```vue
<template>
  <p>hello</p>
</template>
```

after

```vue
<template>
  <p>{{ $t('hello') }}</p>
</template>

<i18n>
{
  "": {
     "": "hello"	
  }
}
</i18n>
```

**Comment by kazupon** [comment]
I think this feature is good! because it eases the pain of supporting i18n for hard-coded messages.

It doesn't completely solve the problem of inserting `keys' and `$t` functions or etc, however, it does ease all the manual work of extracting hard-coded messages and inserting `$t`.

In addition, I hope `key` also has a default `message` inserted.
So, it could be applied as the key directly, depending on the SFC use case or message.

**Comment by ota-meshi** [comment]
I think it makes more sense to provide the Suggestions.
https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions

If it's provided by autofix, it would be difficult for humans to modify many of the keys that were used provisionally by many autofixes.

**Comment by kazupon** [comment]
@ota-meshi 
Thank you for your advice!

> I think it makes more sense to provide the Suggestions.
> https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions

Yes! Our use-case for this suggestion is for SFCs that don't support i18n at all, and I won't be using this fix the second time around.

So it can't be fixed automatically, I think it makes sense to support this feature as a suggestion, and then support it one by one with VSCode manually.

**Comment by kiibo382** [comment]
Thank you for your advice!
Great!
I think it would be better to use Suggestions for this feature, too.
